// import './js/testing/authTest';
// import './js/switcher';
// import './js/best-sellers/topBooks';
// import './js/utils/slider';
// // import './js/testing/authTest';
// import './js/components/header/index';
// // import './js/best-sellers/topBooks';
// import './js/components/best-sellers/topBooks';
// import './js/components/form/form';
// import './js/components/single-book-popup/single-book-popup';
